### ISSUE TITLE
Visualizable data representation of the State machine

### ISSUE THREAD

**Issue by fontanka16** [nblumhardt/stateless#13]
This is not an issue per se, but i am looking for a way to turn my existing State machines into flow charts of some sort. [People say that it is good for you](http://www.embeddedrelated.com/showarticle/723.php),
To be able to achive this i reckon i would have to turn my state machine into some kind of data structure that is more easy to visualize, like a 2-dimensional array or something. I would then turn it into JSON and expose it to some SVG JavaScript library to make it all shiny.

I'm quite new to Stateless, but i wonder if anyone has done anything like this and if it is possible.

**Comment by oysteinkrog** [comment]
Have you seen this?
https://visualstudiogallery.msdn.microsoft.com/058b633d-6919-4585-8018-22886e48337e

**Comment by nblumhardt** [comment]
Wow - I hadn't! Thanks @oysteinkrog for the link! :-)

**Comment by fontanka16** [comment]
Great stuff!
It looks very promising. Thanks!

I have made some progress when it comes to introspection but nothing to show yet. Maybe extending this tool to degenerate the xml is a better approach.
