### ISSUE TITLE
Is it possible to support to have multiple state at once?

### ISSUE THREAD

**Issue by mahmoud690** [nblumhardt/stateless#16]
I know it violates FSM but it is also accepted as an extension too. (check this : http://en.wikipedia.org/wiki/State_diagram#Other_extensions and this for an example : https://today.java.net/article/2009/09/06/finite-state-machine-supporting-concurrent-states)

Is it possible to support it?

**Comment by nblumhardt** [comment]
Hi Mahmoud - no, not in Stateless's design. It would be fascinating to see a library of similar flavour built for this scenario. Thanks for the note!

**Comment by mahmoud690** [comment]
here is an example : https://today.java.net/article/2009/09/06/finite-state-machine-supporting-concurrent-states (as I mentioned above too)
