### ISSUE TITLE
how can i know the source state?

### ISSUE THREAD

**Issue by woshihuo12** [nblumhardt/stateless#22]
for example:

i have 3 states: A B C and A,B can go state C...so when i in OnEnterC()  how can i know the source is A or B? 

very thanks....

**Comment by nblumhardt** [comment]
Hi - you need to use the `OnEntry(t => { ... })` overload. The `t` parameter is a `Transition` object that indicates the source and target states. Hope this helps!

**Comment by woshihuo12** [comment]
thanks very much..
