### ISSUE TITLE
Force State

### ISSUE THREAD

**Issue by KingKnecht** [nblumhardt/stateless#27]
Hi,
is there a possibility to force the state machine to switch into certain state? E.g. if I have undo functionality in my application it could be necessary to set a certain state after an undo command.

**Comment by HenningNT** [comment]
Yes, and no.
You "force" the state change by firing triggers, so if you keep track of the undoable user actions you could store the   corresponding undo-trigger for each trigger.

But are you asking about UI state, or the state of whatever data the application is processing?


----- Opprinnelig melding -----
Fra: "sbardos" <notifications@github.com>
Sendt: ‎10.‎08.‎2015 16:38
Til: "nblumhardt/stateless" <stateless@noreply.github.com>
Emne: [stateless] Force State (#27)

Hi,
is there a possibility to force the state machine to switch into certain state? E.g. if I have undo functionality in my application I could be necessary to set a certain state after an undo command.

**Comment by KingKnecht** [comment]
I'm talking about the data being processed. Let's imagine I have a state machine for a monopoly game. Each state represents a phase of the game i.e. 
GameStarts
PlayerRolls
PlayerLandsOnProperty (FreeParking, GoToJail, Go, etc)
PlayerTrades
PlayerPurchasesProperty
PlayerPurchasesHouses
PlayerPurchasesHotels
PlayerPaysRent
PlayerBankrupts
etc.

Now, imagine the player purchases a property and then decides that this was a mistake and wants to undo the last action. Then I have to restore the properties owned by the player, the credits of the player etc. And at the end I have to set the state to the point before the player purchased a property.

Ok, I could keep track of the states and have a trigger allowing to jump back to the previous state.
For my use-case a stateMachine.SetState(State.PlayerRolls) would be nice. This would avoid additional configuration for the "back-trigger" and would save the extra triggers.

**Comment by KingKnecht** [comment]
Another problem that I see, is that going to a state by firing triggers would have side effects (methods are executed by entering the state) which is not necessary when undo/redo, because game-states (not state machine states) have already been restored by the undo/redo functionality. So, stateMachine.SetState(State.xxx) should not execute any methods.

**Comment by HenningNT** [comment]
I guess it would only be possible to undo a single action, and only a few actions would be eligible for undoing?

Could you store a copy of the game state machine? So if the user wants to undo a purchase the backup state machine is copied back onto the active state machine.

----- Opprinnelig melding -----
Fra: "sbardos" <notifications@github.com>
Sendt: ‎10.‎08.‎2015 18:35
Til: "nblumhardt/stateless" <stateless@noreply.github.com>
Kopi: "HenningNT" <henning.negaardtorsteinsen@gmail.com>
Emne: Re: [stateless] Force State (#27)

Another problem that I see, is that going to a state by firing triggers would have side effects (methods are executed by entering the state) which is not necessary when undo/redo, because game-states (not state machine states) have already been restored by the undo/redo functionality. So, stateMachine.SetState(State.xxx) should not execute any methods.

**Comment by KingKnecht** [comment]
Yes, only a few actions.

Well, if making a copy is possible depends on Stateless, I think. Does Stateless support cloning/serialization?

**Comment by KingKnecht** [comment]
At the moment I think something simple like this will do:
```
 public void SetState(TState state)
        {
            State = state;
        }
```
and the we can do this:

```
 [Test]
        public void SetStateAndContinueStateMachine()
        {
            var sm = new StateMachine<State,Trigger>(State.A);

            sm.Configure(State.A)
                .Permit(Trigger.X, State.B);

            sm.Configure(State.B)
                .Permit(Trigger.Y, State.C);
    
            sm.Fire(Trigger.X);

            sm.SetState(State.A);

            sm.Fire(Trigger.X);

            Assert.AreEqual(sm.State, State.B);
        }
```

**Comment by nblumhardt** [comment]
Hi folks - already available like this:

```csharp
var state = State.GameStarted;

// Store the state externally, use functions to access it
var sm = new StateMachine<State,Trigger>(() => state, s => state = value);

// <snip>

// Set state without any side-effects
state = State.PlayerReady;
```

HTH!
Nick

**Comment by nblumhardt** [comment]
(Yes, the `StateMachine<,>` is, in fact, stateless. Hence the obtuse name ;-))

**Comment by KingKnecht** [comment]
Excellent!
