### ISSUE TITLE
Tagging in source tree to match NuGet package releases.

### ISSUE THREAD

**Issue by f-camera** [nblumhardt/stateless#40]
Could you please provide tagging or branching (sorry, I'm not an expert) on the source repository so that it's easier to find out what are the sources exactly matching the released NuGet packages version?

Thanks in advance.

**Comment by nblumhardt** [comment]
Hi there - currently you can find this information here:

https://ci.appveyor.com/project/NicholasBlumhardt/stateless/history

I'll take a look at what would be required to support tagging next time I tinker with the build; thanks for the suggestion.

**Comment by f-camera** [comment]
Thanks. By now I consider the request satisfied.
